### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mostafa0017** [brz/Breez-ClickOnce#3]
I can't get this addon to work on Firefox or even Chrome, and both times I installed it "breezclickoncehelper.exe" wasn't installed nor was I prompted to install it and all I got was two messages in Firefox, one about privacy and the other about access privileges to all sites which I granted.
I had to install "breezclickoncehelper.exe" manually from the website and restarted my PC but it didn't work either and if I tried to start the helper manually it says : "There was an error installing Breez ClickOnce Helper"
And when I visit the website it says:
Current extension installation status: ✅installed
But of course Clickonce doesn't work across the web.

**Comment by brz** [comment]
Hey mostafa0017
The helper application installs itself to "C:\Users\X\AppData\Local\Breez\ClickOnceHelper".
Do you have any policies or anti-virus active that prevent write access to those folders?

Also, the extension installation status only represents the extension itself, not the helper application. So it's quite normal that you get this message.

**Comment by mostafa0017** [comment]
On my other computer I Stopped my Antivirus (Kaspersky, quitted from system tray) and tried to install again, and the same thing happened, no folder "C:\Users\X\AppData\Local\Breez" was created, and the helper wasn't installed.

**Comment by mostafa0017** [comment]
Any suggestions ? any log I can look at to understand what's happening wrong ?

**Comment by brz** [comment]
[breezclickoncehelper.zip](https://github.com/brz/Breez-ClickOnce/files/12520361/breezclickoncehelper.zip)
Can you please try using the helper application in the attachment? It should give a more precise error message.
Please use CTRL+C to copy the message that pops up in the dialogbox.

**Comment by mostafa0017** [comment]
I run the exe and it said "Breez ClickOnce Helper was installed successfully".
I then closed and reopened Firefox and tried clickonce on a website that works fine under Edge IE mode, but it didn't do anything when I clicked the button that would launch the clickonce instance.

**Comment by brz** [comment]
Does this ClickOnce demo application work for you in Firefox?
[HelloClickOnce](https://bayden.com/test/clickonce/HelloClickOnce.application)

Is the ClickOnce application you are trying to launch public? If so, can you post the link here?
Also please make sure that the server is returning the correct content-type for clickonce applications (application/x-ms-application) and that the url contains ".application".

**Comment by mostafa0017** [comment]
The demo works fine.
The application I am trying to launch isn't public.
I tried again, and this time took a look at the console in Firefox and sadly found multiple lines saying.
Blocked loading mixed active content “http://10.0.11.9/html/IRC.application?addr=10.0.11.9&sessionKey=4a537d7301bc052e5ff867e769230855&lang=en&port=443&alt_mode=0&cofc_goback=false”
Upon clicking one of those links, the application launched successfully.
And according to this:
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default
This was blocked for mixxing http with https
Apparently this issue had nothing to do with your application, but I still stand by my first statement that I never found an "AppData\Local\Breez\ClickOnceHelper" folder when I installed the add-on, nor did I get an installation prompt for the helper.
I may try to reinstall the add-on and see if it will work normally without installing the helper manually.

**Comment by mostafa0017** [comment]
OK, I just tried, and the helper only gets installed when I do so manually.

**Comment by brz** [comment]
You will get prompted to install the helper application when you try to open a clickonce application. And the prompt will only appear if the helper application is not already installed.

For example: I uninstalled the helper application and clicked on the HelloClickOnce demo I mentioned above:

![afbeelding](https://github.com/brz/Breez-ClickOnce/assets/1662000/b194fee2-6843-43b6-933a-42053a964ca1)

**Comment by mostafa0017** [comment]
OK, that actually worked as described, I just thought that the helper would be installed silently in the background by the add-on somehow (I know that add-ons don't have such capabilities or access, but I didn't think about it much).
Ok, thank you and sorry for bothering you with my nuisance.

**Comment by brz** [comment]
No problem. Glad we could sort it out.
